# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 09 Aug 2022 19:42:01 +0000
*               @ALL          1
*               @user         8
