<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: manueles
 * Date: Tue, 09 Aug 2022 23:04:49 +0200
 */

$conf['title'] = '';
$conf['template'] = 'starter';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'Manueles';
$conf['proxy']['pass'] = '<b>ZG9udXRVU0VSMjRoaW5hdGEhIQ==';
