# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 09 Aug 2022 19:42:01 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

manueles:$2y$10$BzrUhwjbHS2F9U7f6slzxOYsIrsCyPTij0TGcKk7U4hKTlNz0j0hO:Manueles Rodriguez Hyuga:overwave.industries@gmail.com:admin,user
